import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import type { MatchWithJob } from '@jobmatch/shared'
import { apiClient } from '../../lib/apiClient'
import { ScoreBadge } from '../matches/ScoreBadge'
import styles from './JobDetailPanel.module.css'

export function JobDetailPanel({ match }: { match: MatchWithJob }) {
  const [rationale, setRationale] = useState(match.rationale)
  const [regenerating, setRegenerating] = useState(false)

  async function handleRegenerate() {
    setRegenerating(true)
    try {
      const result = await apiClient.regenerateRationale(match.jobId)
      setRationale(result.rationale)
    } finally {
      setRegenerating(false)
    }
  }

  const { job } = match

  return (
    <main className="page">
      <Link to="/matches" className={styles.back}>
        ← Back to matches
      </Link>

      <div className={styles.card}>
        <div className={styles.header}>
          <div>
            <h1 className={styles.title}>{job.title}</h1>
            <p className={styles.company}>
              {job.company} · {job.location}
            </p>
            <div className={styles.meta}>
              <span className={styles.tag}>{job.workplaceType}</span>
              <span className={styles.tag}>{job.seniority}</span>
              <span className={styles.tag}>{job.employmentType.replace('_', ' ')}</span>
              {job.salaryRange && (
                <span className={styles.tag}>
                  {job.salaryRange.currency} {Math.round(job.salaryRange.min / 1000)}k–
                  {Math.round(job.salaryRange.max / 1000)}k
                </span>
              )}
              <ScoreBadge score={match.score} />
            </div>
          </div>
          <a href={job.applyUrl} target="_blank" rel="noopener noreferrer" className={styles.applyButton}>
            Apply on company site ↗
          </a>
        </div>

        <div className={styles.rationaleBox}>
          <div className={styles.rationaleHeader}>
            <h4>Why this match</h4>
            <button className={styles.regenerateButton} onClick={handleRegenerate} disabled={regenerating}>
              {regenerating ? 'Regenerating…' : 'Regenerate'}
            </button>
          </div>
          <p className={styles.rationaleText}>{rationale}</p>
          <p className={styles.mockNote}>
            Generated by a mocked Azure AI Foundry client — see README for the real integration design.
          </p>
        </div>

        <div className={styles.section}>
          <h3>About this role</h3>
          <p>{job.description}</p>
        </div>

        <div className={styles.section}>
          <h3>Requirements</h3>
          <ul>
            {job.requirements.map((req) => (
              <li key={req}>{req}</li>
            ))}
          </ul>
        </div>

        {job.niceToHave.length > 0 && (
          <div className={styles.section}>
            <h3>Nice to have</h3>
            <ul>
              {job.niceToHave.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </main>
  )
}
